<?php 
$products = [
    [ "id"=> 0, "imagePath" => "product1.jpg", "discount" => 40, "name"=> "Laptop Hp", "cmimi" => 1299.00, "kategoria"=> "Laptop", "descript" => "HP 17-inch Laptop, 11th Generation Intel Core i5-1135G7, Intel Iris Xe Graphics, 8 GB RAM, 256 GB SSD, Windows 11 Home (17-cn0025nr,Natural Silver)" ],
    [ "id"=> 1, "imagePath" => "product2.jpg", "discount" => 0, "name"=> "Laptop  Bitecool", "cmimi" => 350.00, "kategoria"=> "Laptop", "descript" => "Windows 10 Pro Laptop, BiTECOOL 2022 New 15.6 inches FHD(1920x1080) Display Pc Laptops, with Intel Celeron J4005 Dual Core, 6GB LPDDR4 and 120GB SSD, 2.4G WiFi, BT4.0 and Long Lasting Battery, Mic" ],
    [ "id"=> 2, "imagePath" => "product3.png", "discount" => 20, "name"=> "Asus Vivobook", "cmimi" => 1800.00, "kategoria"=> "Laptop", "descript" => "Windows 10 Home - ASUS recommends Windows 10 Pro for business Up to 11th gen Intel® Core™ i7 processor Up to NVIDIA® GeForce® MX350 Up to 16 GB memory Up to 1 TB SSD Up to 15.6'' FHD NanoEdge display Multiple color option Optional 5.65'' ScreenPad™ with ScreenXpert 2.0" ],
    [ "id"=> 3, "imagePath" => "product4.jpg", "discount" => 30, "name"=> "Gaming mouse rgb", "cmimi" => 30.99, "kategoria"=> "Aksesorë", "descript" => "MANIC G40 Gaming Mouse USB Wired RGB Gaming Mice - PMW 3360 Optical Sensor, 12K DPI Control Optical Control, Huano Switches, 6 Programmable Buttons for PC Windows 7810XPVista Linux [Black]" ],
    [ "id"=> 4, "imagePath" => "product5.jpg", "discount" => 0, "name"=> "Apple EarPods", "cmimi" => 20.99, "kategoria"=> "Aksesorë", "descript" => "Apple EarPods with 3.5mm Headphone Plug - White" ],
    [ "id"=> 5, "imagePath" => "product6.jpg", "discount" => 20, "name"=> "USB Juanwe", "cmimi" => 19.50, "kategoria"=> "Aksesorë", "descript" => "JUANWE 128GB USB 3.0 Flash Drive, Thumb Drive Speed up to 100MB/s, Swivel and LED Indicator Design Memory Stick for PC/Laptop/External Storage Data" ],
    [ "id"=> 6, "imagePath" => "product11.jpeg", "discount" => 0, "name"=> "Tablet Tab E", "cmimi" => 290.00, "kategoria"=> "Phone/Tablet", "descript" => "Samsung Galaxy Tab E 9.6, Dimensionet:241.9 x 149.5 x 8.5 mm, Android 4.4 (KitKat) - EU model, Quad-core 1.3 GHz, 16GB 1.5GB RAM" ],
    [ "id"=> 7, "imagePath" => "product8.jfif", "discount" => 20, "name"=> "Cyberpower PC", "cmimi" => 2199.00, "kategoria"=> "PC", "descript" => "CyberpowerPC Gamer Xtreme VR Gaming PC, Intel Core i5-9400F 2.9GHz, NVIDIA GeForce GTX 1660 6GB, 8GB DDR4, 120GB SSD, 1TB HDD, WiFi Ready & Win 10 Home" ],
    [ "id"=> 8, "imagePath" => "product9.jpg", "discount" => 0, "name"=> "Iphone X", "cmimi" => 600.00, "kategoria"=> "Phone/Tablet", "descript" => "5.8 OLED display, Faster A11 Bionic processor, Glass body, Edge-to-edge display, Facial Recognition, No Home button, Wireless inductive charging, Animoji" ],
    [ "id"=> 9, "imagePath" => "product10.jpg", "discount" => 20, "name"=> "Custom Gaming PC", "cmimi" => 999.99, "kategoria"=> "PC", "descript" => "Windows 10 Home, AMD Ryzen 5 3600, 6x 3.60 GHz, Gigabyte B550M S2H, S. AM4 v2, NVIDIA GeForce GTX 1660 SUPER 6GB, Cooler Master MasterBox MB520, RGB, 16GB DDR4-3200, AMD Standard Kühler, 500 GB | Crucial MX500" ],
    [ "id"=> 10, "imagePath" => "product7.png", "discount" => 0, "name"=> "Ndegjuse Raycon", "cmimi" => 82.00, "kategoria"=> "Aksesorë", "descript" => "Raycon - H20 Wireless Noise-Cancelling Over-the-Ear Headphones" ],
    [ "id"=> 11, "imagePath" => "product12.png", "discount" => 10, "name"=> "Ndegjuse 1more", "cmimi" => 99.00, "kategoria"=> "Aksesorë", "descript" => "Black 1More Comfobuds True Wireless In-Ear Headphones" ],
];
?>